// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqfgyvUVZ1v0b-lmQttO70HZEVQNpb-K0',
    appId: '1:22984193017:web:cfe3b87777dd83b0d28328',
    messagingSenderId: '22984193017',
    projectId: 'intelli-chat-ce521',
    authDomain: 'intelli-chat-ce521.firebaseapp.com',
    storageBucket: 'intelli-chat-ce521.appspot.com',
    measurementId: 'G-CR8BYCJZ54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQT2tpQ4j8Ge9hA-7HrCXzSJaLLL_zKHo',
    appId: '1:22984193017:android:9a7f4f5a8fa31409d28328',
    messagingSenderId: '22984193017',
    projectId: 'intelli-chat-ce521',
    storageBucket: 'intelli-chat-ce521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYTLDgu_oEPEAg8TOfN9UTpmqh-Bvy43s',
    appId: '1:22984193017:ios:388152683c84c146d28328',
    messagingSenderId: '22984193017',
    projectId: 'intelli-chat-ce521',
    storageBucket: 'intelli-chat-ce521.appspot.com',
    androidClientId: '22984193017-buecp2emi3ne41i88kagq14d52ajfj3k.apps.googleusercontent.com',
    iosClientId: '22984193017-f35ng97jujqnctbb3ulcg7oj1aask05c.apps.googleusercontent.com',
    iosBundleId: 'com.example.intellichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYTLDgu_oEPEAg8TOfN9UTpmqh-Bvy43s',
    appId: '1:22984193017:ios:388152683c84c146d28328',
    messagingSenderId: '22984193017',
    projectId: 'intelli-chat-ce521',
    storageBucket: 'intelli-chat-ce521.appspot.com',
    androidClientId: '22984193017-buecp2emi3ne41i88kagq14d52ajfj3k.apps.googleusercontent.com',
    iosClientId: '22984193017-f35ng97jujqnctbb3ulcg7oj1aask05c.apps.googleusercontent.com',
    iosBundleId: 'com.example.intellichat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqfgyvUVZ1v0b-lmQttO70HZEVQNpb-K0',
    appId: '1:22984193017:web:2fb93174b5d0c5cad28328',
    messagingSenderId: '22984193017',
    projectId: 'intelli-chat-ce521',
    authDomain: 'intelli-chat-ce521.firebaseapp.com',
    storageBucket: 'intelli-chat-ce521.appspot.com',
    measurementId: 'G-TE8XS73P76',
  );

}